### ISSUE TITLE
Upgrade to PostCSS 5.x

### ISSUE THREAD

**Issue by valentin-radulescu-hs** [jonathanong/postcss-prefix-selector#3]
- upgrade dependencies in `package.json`
- use `walkRules` instead of `eachRule`(deprecated) [here](https://github.com/jonathanong/postcss-prefix-selector/blob/0ea6367011435af03a1e14bde85a56b2926ddacd/index.js#L10)
- parse [selectors](https://github.com/postcss/postcss/blob/master/docs/api.md#ruleselectors) array instead of splitting [here](https://github.com/jonathanong/postcss-prefix-selector/blob/0ea6367011435af03a1e14bde85a56b2926ddacd/index.js#L12)
- submit plugin to [postcss.parts](http://postcss.parts/)

**Comment by jonathanong** [comment]
:+1:

**Comment by valentin-radulescu-hs** [comment]
And we're live on [`postcss.parts`](https://github.com/himynameisdave/postcss-plugins/blob/master/plugins.json#L1920-L1928) :astonished:
